Repository fatura-brigitta/Proj1-Jelado-10A_F, pull requests merged in 2023-02, with the labels that each got.

#8 Projekt rendben
  .vscode/launch.json
  main.py
Labels: good first issue

#17 kész osztály
  jelek.py
Labels: Important

#18 PDF javítva
  e_inf_22okt_fl.pdf
  e_inf_22okt_jelado.pdf
Labels: Documentation

#20 Megoldás osztály dolgai létrehozva
  Megoldas.py
  jelek.py
  main.py
Labels: New Task, Important, Typo fixing

#22 1. Feladat megoldva
  Megoldas.py
  __pycache__/Jelek.cpython-310.pyc
  __pycache__/Megoldas.cpython-310.pyc
  main.py
Labels: New Task, Important, Issue

#26 2. feladat elvileg kész
  Megoldas.py
  __pycache__/Jelek.cpython-310.pyc
  __pycache__/Megoldas.cpython-310.pyc
  jelek.py
  main.py
Labels: Important

#25 24 readme címkék jelentések
  README.md
Labels: Documentation, It can wait

#28 3. Feladat kb kész
  Megoldas.py
  jelek.py
Labels: New Task, Important

#31 29 4 feladat megoldása
  Megoldas.py
  __pycache__/Jelek.cpython-310.pyc
  __pycache__/Megoldas.cpython-310.pyc
  jelek.py
  main.py
Labels: Important, Issue

#32 5. feladat kész
  Megoldas.py
  __pycache__/Jelek.cpython-310.pyc
  __pycache__/Megoldas.cpython-310.pyc
  main.py
Labels: Important

#35 van try except
  __pycache__/Jelek.cpython-310.pyc
  __pycache__/Megoldas.cpython-310.pyc
  main.py
Labels: It can wait

#41 40 7 feladat
  Megoldas.py
  jelek.py
  kimaradt.txt
  main.py
Labels: Important

#43 42 2 feladat javíitása
  main.py
Labels: It can wait

#45 44 kód szépítése
  .pylintrc
  Megoldas.py
  jelek.py
Labels: Documentation, It can wait

#47 Módosítva
  Megoldas.py
Labels: It can wait

#49 a hibás property feleselges volt, törölve
  Megoldas.py
Labels: It can wait

#51 50 kód szépítése 3
  Jel.py
  Megoldas.py
  main.py
Labels: Important

#54 megoldásban levő függvények public láthatóság
  Megoldas.py
Labels: Important

#55 Tesztelés
  .vscode/settings.json
  kimaradt_OH.txt
  test_Jel.py
  test_Megoldas.py
Labels: New Task, Important

#57 Tesztelés javítva
  test_Megoldas.py
Labels: Bug, Issue
